### ISSUE TITLE
Issue 20 not resolved, when printing i het a blank page

### ISSUE THREAD

**Issue by dustin-auby** [gmuth/ipp-client-kotlin#21] opened 2024-04-26 20:57 UTC
Hi, I'm not sure why point 20 was marked as complete it is not resolved.  

Following on that point I have tried all available formats for multiple printers without success. I have tried on cannon and brother printers. 

I tried these formats
1. PDF
2. Jpeg
3. Png
4. application/octet-stream
5. image/pwg-raster
None of these worked on any of the printers. They do respond and beep but will not print except an empty page

**Comment by gmuth** [comment] 2024-04-27 09:45
duplicate of issue #20

**Comment by gmuth** [comment] 2024-04-27 09:46
duplicate of issue #20

**Closed by gmuth** 2024-04-27 09:46 UTC
Labels: duplicate
